# Generated by Django 4.1.9 on 2023-07-14 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
        ('user', '0002_remove_user_department_professor_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professor',
            name='department',
        ),
        migrations.RemoveField(
            model_name='student',
            name='department',
        ),
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academic.specialization'),
        ),
    ]
